name: "Ruby on Rails CI"
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/nwspk.key
          echo "$ROOT_SSH_KEY" > ~/.ssh/nwspk-root.key
          chmod 600 ~/.ssh/nwspk.key
          chmod 600 ~/.ssh/nwspk-root.key
          cat >> ~/.ssh/config << EOF
          Host nwspk
            HostName 139.59.188.50
            User deploy
            IdentityFile ~/.ssh/nwspk.key
            StrictHostKeyChecking no
          Host nwspk-root
            HostName 139.59.188.50
            User root
            IdentityFile ~/.ssh/nwspk-root.key
            StrictHostKeyChecking no
          EOF
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ROOT_SSH_KEY: ${{ secrets.ROOT_SSH_KEY }}

      - name: Pull latest changes
        run: |
          ssh nwspk "cd /home/deploy/live && git pull"

      - name: Install requirements
        run: |
          ssh nwspk "cd /home/deploy/live && PATH=/home/deploy/.rbenv/shims:$PATH RAILS_ENV=production RACK_ENV=production bundle install --deployment --jobs 2 --without development test"

      - name: Run migrations
        run: ssh nwspk "cd /home/deploy/live && PATH=/home/deploy/.rbenv/shims:$PATH /home/deploy/live/bin/rake db:migrate"
        
      - name: Compile assets
        run: ssh nwspk "cd /home/deploy/live && PATH=/home/deploy/.rbenv/shims:$PATH /home/deploy/live/bin/rake assets:precompile"

      - name: Reload server
        run: ssh nwspk-root 'systemctl restart nwspk-*'

  deploy_staging:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_nwspk_staging
          chmod 600 ~/.ssh/id_nwspk_staging
          cat >> ~/.ssh/config << EOF
          Host nwspk-staging
            HostName staging.newspeak.house
            User deploy
            IdentityFile ~/.ssh/id_nwspk_staging
            StrictHostKeyChecking no
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}

      - name: Pull latest changes
        run: ssh nwspk-staging "cd /var/www/web && git pull"

      - name: Install dependencies
        run: ssh nwspk-staging "cd /var/www/web && source .envrc && export PATH=/home/deploy/.rbenv/shims:$PATH && bundle install"

      - name: Run migrations
        run: ssh nwspk-staging "cd /var/www/web && source .envrc && export PATH=/home/deploy/.rbenv/shims:$PATH && rails db:migrate"

      - name: Compile static assets
        run: ssh nwspk-staging "cd /var/www/web && source .envrc && export PATH=/home/deploy/.rbenv/shims:$PATH && rails assets:precompile"

      - name: Reload application
        run: |
        ssh nwspk-staging "sudo /usr/bin/systemctl restart nwspk-web.service"
        ssh nwspk-staging "sudo /usr/bin/systemctl restart nwspk-sidekick.service"
